NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /
app_bundle:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/routing.yml"
