NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

app_bundle:
    type: rest
    prefix: /
    resource: "@AppBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: "%admin_dashboard_base_url%"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: "%admin_dashboard_base_url%"

#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media