parameters:
    app.services.object_updater_class: AppBundle\Services\ObjectUpdater
    app.services.contribute_dream_class: AppBundle\Services\ContributeDream

services:
    app.services.object_updater:
        class: "%app.services.object_updater_class%"

    app.services.contribute_dream:
        class: "%app.services.contribute_dream_class%"
