sonata_media:
    class:
        media: Application\Sonata\MediaBundle\Document\Media
        gallery: Application\Sonata\MediaBundle\Document\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Document\GalleryHasMedia
    default_context: default
    db_driver: doctrine_mongodb
    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

    providers:
        image:
            resizer: sonata.media.resizer.square