app_dream:
    type: rest
    resource: "@AppBundle/Controller/DreamController.php"

app_faq:
    type: rest
    resource: "@AppBundle/Controller/FaqController.php"

app_users:
   type: rest
   resource: "@AppBundle/Controller/UsersController.php"

app_status:
   type: rest
   resource: "@AppBundle/Controller/StatusController.php"

app_contribute:
   path: /dreams/{slugDream}/contribute
   methods: [POST]
   defaults: { _controller: AppBundle:Contribute:postContribute }
